# -*- coding: utf-8 -*-


def list():
    return {
        'ofstream': 'http://ru.cppreference.com/w/cpp/io/basic_ostream',
        'no matching function for call': 'http://cppstudio.com/post/409/',
        'arguments': 'http://itedu.ru/courses/cpp/functions-in-cpp',
        'functions': 'http://itedu.ru/courses/cpp/functions-in-cpp',
        'candidate expects': 'http://itedu.ru/courses/cpp/functions-in-cpp',
        "expected ‘;’ before": "http://cppstudio.com/post/213/",
        'expected initializer before': 'http://cppstudio.com/post/213/',
        'expected primary-expression': 'http://cppstudio.com/post/213/',
        'expected ‘,’ or ‘;’ before': 'http://cppstudio.com/post/213/',
        'does not name a type': 'http://cppstudio.com/post/271/',
        'expected unqualified-id before': 'http://cppstudio.com/post/213/',
        'empty character constant': 'http://cppstudio.com/post/271/',
        'invalid conversion from ‘const char*’ to ‘char’': 'http://cppstudio.com/post/271/',
        'was not declared in this scope': 'http://cppstudio.com/post/5291/',
        'cannot convert': 'http://cppstudio.com/post/271/',
        'was not declared': 'https://code-live.ru/post/cpp-functions/',
        'ld returned 1 exit status': 'http://cppstudio.com/post/213/',
        'expected ‘;’ after struct definition': 'http://cppstudio.com/post/7008/',
        'has no member named': 'http://cppstudio.com/post/7008/',
        'enumerator value for': 'http://cppstudio.com/post/8106/',
        'enumerat': 'http://cppstudio.com/post/8106/',
        'too few arguments to function': 'http://cppstudio.com/post/396/',
        'expected initializer': 'http://cppstudio.com/post/404/',
        'undefined reference to': 'http://cppstudio.com/post/5291/',
        'type': 'http://cppstudio.com/post/310/',
        'switch': 'http://cppstudio.com/post/5259/',
        'goto': 'http://cppstudio.com/post/5259/',
        'break': 'http://cppstudio.com/post/5259/',
        'stray': 'http://cppstudio.com/post/259/',
        #"+": 'http://cppstudio.com/post/259/',
        # '-': 'http://cppstudio.com/post/259/',
        # '*': 'http://cppstudio.com/post/259/',
        # '/': 'http://cppstudio.com/post/259/',
        # '%': 'http://cppstudio.com/post/259/',
        'lvalue required as increment operand': 'http://cppstudio.com/post/282/',
        'lvalue required as decrement operand': 'http://cppstudio.com/post/282/',
        # '+=': 'http://cppstudio.com/post/279/',
        # '-=': 'http://cppstudio.com/post/279/',
        # '*=': 'http://cppstudio.com/post/279/',
        # '/=': 'http://cppstudio.com/post/279/',
        # '%=': 'http://cppstudio.com/post/279/',
        # '&&': 'http://cppstudio.com/post/297/',
        # '||': 'http://cppstudio.com/post/297/',
        # '!': 'http://cppstudio.com/post/297/',
        'const': 'http://cppstudio.com/post/394/',
        'class': 'http://cppstudio.com/post/439/',
        'private': 'http://cppstudio.com/post/439/',
        'public': 'http://cppstudio.com/post/439/',
        'protected': 'http://cppstudio.com/post/439/',
        'construct': 'http://cppstudio.com/post/439/',
        'static': 'http://cppstudio.com/post/3298/',
        'friend': 'http://cppstudio.com/post/8423/',
        'this': 'http://cppstudio.com/post/8712/',
        'extend': 'http://cppstudio.com/post/10103/',
        'template': 'http://cppstudio.com/post/5165/',
        '.open': 'http://cppstudio.com/post/446/',
        '.close': 'http://cppstudio.com/post/446/',
        'ifstream': 'http://cppstudio.com/post/446/',
        'fstream': 'http://cppstudio.com/post/446/',
        '.getline': 'http://cppstudio.com/post/446/',
        'ios_base': 'http://cppstudio.com/post/446/',
        'try': 'http://cppstudio.com/post/9773/',
        'catch': 'http://cppstudio.com/post/9773/',
        'throw': 'http://cppstudio.com/post/9773/',
        'exception': 'http://cppstudio.com/post/9773/',
        'malloc': 'http://cppstudio.com/post/9088/',
        'free': 'http://cppstudio.com/post/9088/',
        'calloc': 'http://cppstudio.com/post/846/',
        'pointer': 'http://cppstudio.com/post/5828/'
    }